title: My Blog
description: >- # this means to ignore newlines until "baseurl:"
  A simple Jekyll blog with tabs.
baseurl: "" # baseurl should be "" for GitHub Pages, unless you're using a custom domain
url: "https://yourusername.github.io/pen-pencil-review" # the base hostname & protocol for your site
